#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : neon
Version  : 0.33.0
Release  : 3
URL      : https://notroj.github.io/neon/neon-0.33.0.tar.gz
Source0  : https://notroj.github.io/neon/neon-0.33.0.tar.gz
Summary  : HTTP/WebDAV client library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: neon-bin = %{version}-%{release}
Requires: neon-lib = %{version}-%{release}
Requires: neon-license = %{version}-%{release}
Requires: neon-locales = %{version}-%{release}
Requires: neon-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : expat-dev
BuildRequires : file
BuildRequires : krb5-dev
BuildRequires : pkgconfig(libproxy-1.0)
BuildRequires : pkgconfig(openssl)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the source directory of the 'neon' HTTP/WebDAV client library,
which can be bundled inside other packages. For the complete neon
package, see <https://notroj.github.io/neon/>

%package bin
Summary: bin components for the neon package.
Group: Binaries
Requires: neon-license = %{version}-%{release}

%description bin
bin components for the neon package.


%package dev
Summary: dev components for the neon package.
Group: Development
Requires: neon-lib = %{version}-%{release}
Requires: neon-bin = %{version}-%{release}
Provides: neon-devel = %{version}-%{release}
Requires: neon = %{version}-%{release}

%description dev
dev components for the neon package.


%package doc
Summary: doc components for the neon package.
Group: Documentation
Requires: neon-man = %{version}-%{release}

%description doc
doc components for the neon package.


%package lib
Summary: lib components for the neon package.
Group: Libraries
Requires: neon-license = %{version}-%{release}

%description lib
lib components for the neon package.


%package license
Summary: license components for the neon package.
Group: Default

%description license
license components for the neon package.


%package locales
Summary: locales components for the neon package.
Group: Default

%description locales
locales components for the neon package.


%package man
Summary: man components for the neon package.
Group: Default

%description man
man components for the neon package.


%prep
%setup -q -n neon-0.33.0
cd %{_builddir}/neon-0.33.0
pushd ..
cp -a neon-0.33.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719980372
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-static \
--enable-shared \
--enable-threadsafe-ssl=posix \
--with-expat \
--with-libproxy \
--with-ssl=openssl
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-static \
--enable-shared \
--enable-threadsafe-ssl=posix \
--with-expat \
--with-libproxy \
--with-ssl=openssl
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719980372
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/neon
cp %{_builddir}/neon-%{version}/src/COPYING.LIB %{buildroot}/usr/share/package-licenses/neon/44f7289042b71631acac29b2f143330d2da2479e || :
cp %{_builddir}/neon-%{version}/test/COPYING %{buildroot}/usr/share/package-licenses/neon/075d599585584bb0e4b526f5c40cb6b17e0da35a || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang neon
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/neon-config

%files dev
%defattr(-,root,root,-)
/usr/include/neon/ne_207.h
/usr/include/neon/ne_acl.h
/usr/include/neon/ne_acl3744.h
/usr/include/neon/ne_alloc.h
/usr/include/neon/ne_auth.h
/usr/include/neon/ne_basic.h
/usr/include/neon/ne_compress.h
/usr/include/neon/ne_dates.h
/usr/include/neon/ne_defs.h
/usr/include/neon/ne_i18n.h
/usr/include/neon/ne_locks.h
/usr/include/neon/ne_md5.h
/usr/include/neon/ne_pkcs11.h
/usr/include/neon/ne_props.h
/usr/include/neon/ne_redirect.h
/usr/include/neon/ne_request.h
/usr/include/neon/ne_session.h
/usr/include/neon/ne_socket.h
/usr/include/neon/ne_ssl.h
/usr/include/neon/ne_string.h
/usr/include/neon/ne_uri.h
/usr/include/neon/ne_utils.h
/usr/include/neon/ne_xml.h
/usr/include/neon/ne_xmlreq.h
/usr/lib64/libneon.so
/usr/lib64/pkgconfig/neon.pc
/usr/share/man/man3/ne_add_request_header.3
/usr/share/man/man3/ne_addr_destroy.3
/usr/share/man/man3/ne_addr_error.3
/usr/share/man/man3/ne_addr_first.3
/usr/share/man/man3/ne_addr_next.3
/usr/share/man/man3/ne_addr_resolve.3
/usr/share/man/man3/ne_addr_result.3
/usr/share/man/man3/ne_buffer.3
/usr/share/man/man3/ne_buffer_altered.3
/usr/share/man/man3/ne_buffer_append.3
/usr/share/man/man3/ne_buffer_clear.3
/usr/share/man/man3/ne_buffer_concat.3
/usr/share/man/man3/ne_buffer_create.3
/usr/share/man/man3/ne_buffer_destroy.3
/usr/share/man/man3/ne_buffer_finish.3
/usr/share/man/man3/ne_buffer_grow.3
/usr/share/man/man3/ne_buffer_ncreate.3
/usr/share/man/man3/ne_buffer_zappend.3
/usr/share/man/man3/ne_calloc.3
/usr/share/man/man3/ne_close_connection.3
/usr/share/man/man3/ne_forget_auth.3
/usr/share/man/man3/ne_get_error.3
/usr/share/man/man3/ne_get_request_flag.3
/usr/share/man/man3/ne_get_response_header.3
/usr/share/man/man3/ne_get_scheme.3
/usr/share/man/man3/ne_get_server_hostport.3
/usr/share/man/man3/ne_get_session_flag.3
/usr/share/man/man3/ne_get_status.3
/usr/share/man/man3/ne_has_support.3
/usr/share/man/man3/ne_i18n_init.3
/usr/share/man/man3/ne_iaddr_cmp.3
/usr/share/man/man3/ne_iaddr_free.3
/usr/share/man/man3/ne_iaddr_make.3
/usr/share/man/man3/ne_iaddr_parse.3
/usr/share/man/man3/ne_iaddr_print.3
/usr/share/man/man3/ne_iaddr_raw.3
/usr/share/man/man3/ne_iaddr_reverse.3
/usr/share/man/man3/ne_iaddr_typeof.3
/usr/share/man/man3/ne_malloc.3
/usr/share/man/man3/ne_oom_callback.3
/usr/share/man/man3/ne_print_request_header.3
/usr/share/man/man3/ne_qtoken.3
/usr/share/man/man3/ne_realloc.3
/usr/share/man/man3/ne_request_create.3
/usr/share/man/man3/ne_request_destroy.3
/usr/share/man/man3/ne_request_dispatch.3
/usr/share/man/man3/ne_response_header_iterate.3
/usr/share/man/man3/ne_session_create.3
/usr/share/man/man3/ne_session_destroy.3
/usr/share/man/man3/ne_session_proxy.3
/usr/share/man/man3/ne_session_socks_proxy.3
/usr/share/man/man3/ne_session_system_proxy.3
/usr/share/man/man3/ne_set_addrlist.3
/usr/share/man/man3/ne_set_connect_timeout.3
/usr/share/man/man3/ne_set_error.3
/usr/share/man/man3/ne_set_proxy_auth.3
/usr/share/man/man3/ne_set_read_timeout.3
/usr/share/man/man3/ne_set_request_body_buffer.3
/usr/share/man/man3/ne_set_request_body_fd.3
/usr/share/man/man3/ne_set_request_body_provider.3
/usr/share/man/man3/ne_set_request_flag.3
/usr/share/man/man3/ne_set_server_auth.3
/usr/share/man/man3/ne_set_session_flag.3
/usr/share/man/man3/ne_set_useragent.3
/usr/share/man/man3/ne_shave.3
/usr/share/man/man3/ne_sock_exit.3
/usr/share/man/man3/ne_sock_init.3
/usr/share/man/man3/ne_ssl_cert_cmp.3
/usr/share/man/man3/ne_ssl_cert_export.3
/usr/share/man/man3/ne_ssl_cert_free.3
/usr/share/man/man3/ne_ssl_cert_identity.3
/usr/share/man/man3/ne_ssl_cert_import.3
/usr/share/man/man3/ne_ssl_cert_issuer.3
/usr/share/man/man3/ne_ssl_cert_read.3
/usr/share/man/man3/ne_ssl_cert_signedby.3
/usr/share/man/man3/ne_ssl_cert_subject.3
/usr/share/man/man3/ne_ssl_cert_write.3
/usr/share/man/man3/ne_ssl_clicert_decrypt.3
/usr/share/man/man3/ne_ssl_clicert_encrypted.3
/usr/share/man/man3/ne_ssl_clicert_free.3
/usr/share/man/man3/ne_ssl_clicert_name.3
/usr/share/man/man3/ne_ssl_clicert_owner.3
/usr/share/man/man3/ne_ssl_clicert_read.3
/usr/share/man/man3/ne_ssl_dname_cmp.3
/usr/share/man/man3/ne_ssl_readable_dname.3
/usr/share/man/man3/ne_ssl_set_verify.3
/usr/share/man/man3/ne_ssl_trust_cert.3
/usr/share/man/man3/ne_ssl_trust_default_ca.3
/usr/share/man/man3/ne_status.3
/usr/share/man/man3/ne_strdup.3
/usr/share/man/man3/ne_strhash.3
/usr/share/man/man3/ne_strndup.3
/usr/share/man/man3/ne_strparam.3
/usr/share/man/man3/ne_token.3
/usr/share/man/man3/ne_version_match.3
/usr/share/man/man3/ne_version_string.3
/usr/share/man/man3/ne_vstrhash.3
/usr/share/man/man3/ne_xml_create.3
/usr/share/man/man3/ne_xml_destroy.3
/usr/share/man/man3/neon.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/neon/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libneon.so.27.6.0
/usr/lib64/libneon.so.27
/usr/lib64/libneon.so.27.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/neon/075d599585584bb0e4b526f5c40cb6b17e0da35a
/usr/share/package-licenses/neon/44f7289042b71631acac29b2f143330d2da2479e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/neon-config.1

%files locales -f neon.lang
%defattr(-,root,root,-)

